# Generated by Django 3.0 on 2020-01-30 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('FName', models.CharField(max_length=30)),
                ('Age', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('FName', models.CharField(max_length=30)),
                ('Nick', models.CharField(max_length=30)),
                ('Age', models.CharField(max_length=2)),
                ('Photo', models.ImageField(upload_to='fotos/')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('ID_Owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Configuration.Owner')),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('Pricepool', models.CharField(max_length=10)),
                ('MVP', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Configuration.Player')),
                ('Winner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Configuration.Team')),
            ],
        ),
        migrations.CreateModel(
            name='TournamentTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Position', models.CharField(max_length=3)),
                ('ID_Team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Configuration.Team')),
                ('ID_Tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Configuration.Tournament')),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='ID_Team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Configuration.Team'),
        ),
    ]
