# Generated by Django 3.0 on 2020-01-30 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Configuration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='ID_Team',
            field=models.ForeignKey(on_delete=models.SET('null'), to='Configuration.Team'),
        ),
        migrations.AlterField(
            model_name='team',
            name='ID_Owner',
            field=models.ForeignKey(on_delete=models.SET('null'), to='Configuration.Owner'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='MVP',
            field=models.ForeignKey(on_delete=models.SET('null'), to='Configuration.Player'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='Winner',
            field=models.ForeignKey(on_delete=models.SET('null'), to='Configuration.Team'),
        ),
        migrations.AlterField(
            model_name='tournamentteam',
            name='ID_Team',
            field=models.ForeignKey(on_delete=models.SET('null'), to='Configuration.Team'),
        ),
        migrations.AlterField(
            model_name='tournamentteam',
            name='ID_Tournament',
            field=models.ForeignKey(on_delete=models.SET('null'), to='Configuration.Tournament'),
        ),
    ]
