# Generated by Django 3.0 on 2020-02-10 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Configuration', '0002_auto_20200130_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='ID_Team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Configuration.Team'),
        ),
        migrations.AlterField(
            model_name='team',
            name='ID_Owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Configuration.Owner'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='MVP',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Configuration.Player'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='Winner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Configuration.Team'),
        ),
        migrations.AlterField(
            model_name='tournamentteam',
            name='ID_Team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Configuration.Team'),
        ),
        migrations.AlterField(
            model_name='tournamentteam',
            name='ID_Tournament',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Configuration.Tournament'),
        ),
    ]
