# Generated by Django 3.0 on 2020-02-11 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Configuration', '0003_auto_20200210_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='Photo',
            field=models.ImageField(blank=True, null=True, upload_to='fotos'),
        ),
    ]
